"""empty message

Revision ID: 39b4d6910d0c
Revises: 195f8e82c332
Create Date: 2025-12-30 11:32:51.003624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b4d6910d0c'
down_revision = '195f8e82c332'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=1), nullable=False),
    sa.Column('change', sa.Date(), nullable=True),
    sa.Column('sum_', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('money')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('sum_', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.INTEGER(), nullable=False),
    sa.Column('cat', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('change', sa.DATETIME(), nullable=True),
    sa.Column('users', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transactions')
    # ### end Alembic commands ###
