"""empty message

Revision ID: 3b6495587588
Revises: 39b4d6910d0c
Create Date: 2025-12-30 11:33:24.066196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6495587588'
down_revision = '39b4d6910d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=False),
    sa.Column('users', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('sum_', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('cat', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('change', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money')
    # ### end Alembic commands ###
