"""empty message

Revision ID: 195f8e82c332
Revises: f70aa3ba3b04
Create Date: 2025-12-13 09:51:15.975061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195f8e82c332'
down_revision = 'f70aa3ba3b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.add_column(sa.Column('users', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money', schema=None) as batch_op:
        batch_op.drop_column('users')

    # ### end Alembic commands ###
