"""empty message

Revision ID: c9d78d1d2db9
Revises: 6972a4e0addd
Create Date: 2025-11-21 22:07:00.914382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d78d1d2db9'
down_revision = '6972a4e0addd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=64), nullable=False),
    sa.Column('text', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtitle'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
