"""empty message

Revision ID: f42f6fa1b7c2
Revises: df1f58afb6b9
Create Date: 2025-11-21 08:03:45.637463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42f6fa1b7c2'
down_revision = 'df1f58afb6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=64), nullable=False),
    sa.Column('text', sa.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtitle'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###
